CREATE SCHEMA WaveStyled;

CREATE TABLE Wardrobe {

 	pieceID INT PRIMARY KEY,
 	R_COLOR INT,
 	G_COLOR INT,
 	B_COLOR INT,
 	TYPE VARCHAR(2),
 	RECENT_DATE_WORN DATE,
 	TIMES_WORD INT,
 	RATING FLOAT(3,2),
 	OC_FORMAL BIT,
 	OC_SEMI_FORMAL BIT,
 	OC_CASUAL BIT,
 	OC_WORKOUT BIT,
 	OC_OUTDOORS BIT,
 	OC_COMFY BIT,
 	WE_COLD BIT,
 	WE_HOT BIT,
 	WE_RAINY BIT,
 	WE_SNOWY BIT,
 	WE_AVG_TMP BIT


}

CREATE TABLE Outfits {
	OUTFIT_ID INT PRIMARY KEY,
	HAT INT,
	SHIRT INT,
	SWEATER INT,
	JAKCET INT,
	BOTTOM_LAYER INT,
	SHOES INT,
	MISC INT,
	TIMES_WORN INT,
	RECENT_DATE_WORN DATE,
	FIT_SCORE FLOAT(3,2),
	OC_FORMAL BIT,
 	OC_SEMI_FORMAL BIT,
 	OC_CASUAL BIT,
 	OC_WORKOUT BIT,
 	OC_OUTDOORS BIT,
 	OC_COMFY BIT,
 	WE_COLD BIT,
 	WE_HOT BIT,
 	WE_RAINY BIT,
 	WE_SNOWY BIT,
 	WE_AVG_TMP BIT

}
